name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: ‍💻 Deploy Migrations to Staging
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v3

      - name: 🐧 Use Supabase CLI of latest version
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 📦 Link Supabase Project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: 🩹 Repair migrations history
        run: supabase migration repair --status reverted 20251123145249 20251124170709

      - name: 📦 Apply Migrations
        run: supabase db push
